All Expansion tab implemented
sofia819/mount_recorder_client pull request #12
Opened 2020-09-07 23:12 UTC by EvanM27

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)

## Pull request type

 

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?
no ability to display all expansion userMounts on one table

Issue Number: 3

## What is the new behavior?
A new all tab displays all expansion userMounts on one table

-
-
-

## Other information
column spacing breaks on this table
![All Tab](https://user-images.githubusercontent.com/30082233/92419864-01e0d680-f13e-11ea-9289-4aaa6abe0b92.gif)

2020-09-07 23:24 UTC, sofia819 commented
Can you make it so that the `All` tab isn't the second tab? I am thinking it should be the left most tab. You can give it an index of -1 instead.

2020-09-07 23:37 UTC, sofia819 requested changes
Can you make it so that the All tab isn't the second tab? I am thinking it should be the left most tab. You can give it an index of -1 instead.

2020-09-08 00:36 UTC, sofia819 commented on src/utils/constants.js
> +  1: "All",
Remove this

2020-09-08 00:37 UTC, sofia819 approved these changes
Minor comments but LGTM

2020-09-08 00:37 UTC, sofia819 commented on src/utils/constants.js
> +  "-1": "all",
Uppercase `All`

2020-09-08 00:40 UTC, EvanM27 commented on src/utils/constants.js
> +  "-1": "all",
Resolved

2020-09-08 00:41 UTC, merged